[build]

[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
commands = [
  "python3 -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
