[build]

[phases.setup]
nixPkgs = ["python3", "python3Packages.virtualenv", "gcc", "postgresql_16.dev"]

[phases.install]
commands = [
  "python3 -m venv /tmp/venv",
  "/tmp/venv/bin/pip install --upgrade pip",
  "/tmp/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/tmp/venv/bin/python -m flask --app src.main db upgrade && /tmp/venv/bin/python -m gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
