[build]

[phases.setup]
nixPkgs = ["python3", "python3Full", "python3Packages.pip", "gcc", "postgresql_16.dev"]

[phases.install]
commands = [
  "python3 -m ensurepip --upgrade",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
