services:
  - type: web
    name: chamados-manutencao
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chamados-db
          property: connectionString
    healthCheckPath: /health
    
  - type: pserv
    name: chamados-db
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.postgres
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: chamados-db
    databaseName: chamados
    user: chamados_user

