"""Adiciona coluna descricao ao tb_turnos

Revision ID: f9fac2e7aaaa
Revises: 
Create Date: 2025-06-23 19:36:43.841744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fac2e7aaaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_contatos_notificacao_manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_locais_apontamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_nao_conformidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tb_status_chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=4), nullable=True),
    sa.Column('cliente_nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_email', sa.String(length=120), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=True),
    sa.Column('email_requisitante', sa.String(length=120), nullable=False),
    sa.Column('telefone_requisitante', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('id_nao_conformidade', sa.Integer(), nullable=True),
    sa.Column('id_local_apontamento', sa.Integer(), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_inicio_atendimento', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao_manutencao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao_admin', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resposta_tecnico', sa.Text(), nullable=True),
    sa.Column('anexos', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_local_apontamento'], ['tb_locais_apontamento.id'], ),
    sa.ForeignKeyConstraint(['id_nao_conformidade'], ['tb_nao_conformidades.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['tb_status_chamado.id'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['tb_turnos.id'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['tb_unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolo')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['tb_perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_historico_chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('detalhes_adicionais', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['tb_chamados.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_historico_notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=True),
    sa.Column('tipo_notificacao', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=120), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('status_envio', sa.String(length=20), nullable=False),
    sa.Column('detalhes_erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['tb_chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_historico_notificacoes')
    op.drop_table('tb_historico_chamado')
    op.drop_table('tb_users')
    op.drop_table('tb_chamados')
    op.drop_table('tb_unidades')
    op.drop_table('tb_turnos')
    op.drop_table('tb_status_chamado')
    op.drop_table('tb_perfis')
    op.drop_table('tb_nao_conformidades')
    op.drop_table('tb_locais_apontamento')
    op.drop_table('tb_contatos_notificacao_manutencao')
    # ### end Alembic commands ###
