"""tabela historico chamada

Revision ID: b19299a5c21b
Revises: f9fac2e7aaaa
Create Date: 2025-07-17 09:41:39.875303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19299a5c21b'
down_revision = 'f9fac2e7aaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_historico_chamado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anexos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_historico_chamado', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('anexos')

    # ### end Alembic commands ###
