[phases.setup]
commands = []

[phases.install]
commands = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
commands = [
  "gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
]
