# nixpacks.toml

[phases.setup]
commands = []

[phases.install]
commands = [
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  # 1) Aplica migrações (usando sua função upgrade() diretamente)
  "python -c 'from flask_migrate import upgrade; upgrade()'",
  
  # 2) Insere dados iniciais (seed)
  "python -c 'import src.main; src.main.inserir_dados_iniciais()'",

  # 3) Inicia o servidor
  "gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
]

